
# Hatari setup:
# sudo apt install hatari
# sudo cp emutos-512k-1.3/etos512us.img /usr/share/hatari/tos.img

run-4thcore:
	hatari --mono --cpuclock 32 --auto C:\4THCORE.PRG --confirm-quit \
	false .

run-hconsole:
	./emulator/run-in-hatari.py
